---
- name: main playbook for workstation setup
  hosts: workstations
  connection: local
  roles:
    - { role: packaging, become: yes }
    - { role: configuration, become: no }
    - { role: geerlingguy.docker, become: yes }
