---
- hosts: workstations
  
  vars:
    packages: [vim, synapse, terminator, htop, shutter, firefox, git, screen]
  
  sudo: yes
  
  tasks:
  - name: ensure packages are at the latest version
    apt: pkg={{ item }} state=latest
    with_items: packages
    register: apt_latest
  
  - name: log package changes to latest
    debug: msg="{{item}}"
    with_items: apt_latest.stdout_lines
  
  - name: ensure google linux package signing key is present
    apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  
  - name: ensure google chrome repository is present
    apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present
  
  - name: ensure google chrome is at the latest version
    apt: pkg=google-chrome-stable state=latest

  - name: ensure textadept repository is present
    apt_repository: repo='ppa:nilarimogard/webupd8' state=present
  
  - name: ensure textadept is at the latest version
    apt: pkg=textadept state=latest
  
  - name: checkout my configuration files
    sudo: no
    git: >
      repo=git@github.com:tnguyen1/configuration.git
      dest=/home/{{ ansible_user_id }}/configuration

  - name: create vimrc symlink
    sudo: no
    file: >
      src=/home/{{ ansible_user_id }}/configuration/vimrc
      dest=/home/{{ ansible_user_id }}/.vimrc
      state=link