---
- name: ensure packages are at the latest version
  apt: pkg={{ item }} state=latest
  with_items: packages

- name: ensure google linux package signing key is present
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: ensure google chrome repository is present
  apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' state=present

- name: ensure google chrome is at the latest version
  apt: pkg=google-chrome-stable state=latest

- name: ensure textadept repository is present
  apt_repository: repo='ppa:nilarimogard/webupd8' state=present

- name: ensure textadept is at the latest version
  apt: pkg=textadept state=latest

- name: ensure purple-hangouts for pidgin is at latest version
  apt: pkg={{ item }} state=latest
  with_items:
    - purple-hangouts
    - pidgin-hangouts

- name: ensure Oracle Java 8 APT repository is present
  apt_repository: repo='ppa:webupd8team/java'

- name: ensure Oracle licence is accepted
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: ensure Oracle Java 8 is at latest version
  apt: pkg=oracle-java8-installer state=latest

- name: ensure copyq repository is present
  apt_repository: repo='ppa:noobslab/indicators' state=present

- name: ensure copyq is at the latest version
  apt: pkg={{ item }} state=latest
  with_items:
    - copyq
    - libqt4-svg

- name: add docker-engine apt key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: ensure docker-engine apt repository is present
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

- name: ensure docker-engine is at the latest version
  apt: pkg=docker-engine state=latest

- name: ensure python-pip is at latest version
  shell: pip install --upgrade pip
