---
- name: ensure packages are at the latest version
  apt: pkg={{ item }} state=latest
  with_items: packages

- name: ensure google linux package signing key is present
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: ensure google chrome repository is present
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present

- name: ensure google chrome is at the latest version
  apt: pkg=google-chrome-stable state=latest

- name: ensure textadept repository is present
  apt_repository: repo='ppa:nilarimogard/webupd8' state=present

- name: ensure textadept is at the latest version
  apt: pkg=textadept state=latest

- name: ensure oracle java repository is present
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: ensure oracle java is at the latest version
  apt: pkg=oracle-java7-installer state=latest