---

packages:
  - zsh
  - vim
  - terminator
  - htop
  - firefox
  - git
  - ack-grep
  - curl
  - autojump
  - tree
  - filezilla
  - lftp
  - openvpn
  - network-manager-openvpn-gnome
  - xtightvncviewer
  - remmina
  - inkscape
  - gimp
  - graphviz
  - gnuplot
  - python-pip
  - libssl-dev
  - fonts-crosextra-caladea
  - fonts-crosextra-carlito
  - spacefm
  - udevil
